swagger: "2.0"
info:
  title: AlgoDex Indexer Service
  description: Service for tracking Algorand accounts and currently opted-in Holdings
  version: ""
host: localhost:80
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /account:
    get:
      tags:
      - account
      summary: list account
      description: List all tracked accounts
      operationId: account#list
      parameters:
      - name: view
        in: query
        description: View to render
        required: false
        type: string
        enum:
        - default
        - full
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AccountTrackedAccountResponseCollection'
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/AccountListAccessDeniedResponseBody'
      schemes:
      - http
    post:
      tags:
      - account
      summary: add account
      description: Add Algorand account(s) to track
      operationId: account#add
      parameters:
      - name: AddRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/AccountAddRequestBody'
          required:
          - address
      responses:
        "200":
          description: OK response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/AccountAddAccessDeniedResponseBody'
      schemes:
      - http
  /account/{address}:
    get:
      tags:
      - account
      summary: get account
      description: Get specific account
      operationId: account#get
      parameters:
      - name: address
        in: path
        description: Public Account address
        required: true
        type: string
        maxLength: 58
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AccountGetResponseBody'
            required:
            - address
            - round
            - holdings
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/AccountGetAccessDeniedResponseBody'
      schemes:
      - http
    delete:
      tags:
      - account
      summary: delete account
      description: Delete Algorand account(s) to track
      operationId: account#delete
      parameters:
      - name: address
        in: path
        required: true
        type: array
        items:
          type: string
        collectionFormat: multi
      responses:
        "200":
          description: OK response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/AccountDeleteAccessDeniedResponseBody'
      schemes:
      - http
  /account/all:
    delete:
      tags:
      - account
      summary: deleteAll account
      description: Delete all tracked algorand account(s).  Used for resetting everything
      operationId: account#deleteAll
      responses:
        "200":
          description: OK response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/AccountDeleteAllAccessDeniedResponseBody'
      schemes:
      - http
  /account/get:
    post:
      tags:
      - account
      summary: getMultiple account
      description: Get account(s)
      operationId: account#getMultiple
      parameters:
      - name: GetMultipleRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/AccountGetMultipleRequestBody'
          required:
          - address
      responses:
        "200":
          description: OK response.
          schema:
            type: array
            items:
              $ref: '#/definitions/AccountResponse'
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/AccountGetMultipleAccessDeniedResponseBody'
      schemes:
      - http
  /account/isWatched:
    post:
      tags:
      - account
      summary: isWatched account
      description: Returns which of the passed accounts are currently being monitored
      operationId: account#isWatched
      parameters:
      - name: IsWatchedRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/AccountIsWatchedRequestBody'
          required:
          - address
      responses:
        "200":
          description: OK response.
          schema:
            type: array
            items:
              type: string
              example: Mollitia nihil rerum a veritatis ipsam suscipit.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/AccountIsWatchedAccessDeniedResponseBody'
      schemes:
      - http
  /inspect/unpack:
    post:
      tags:
      - inspect
      summary: unpack inspect
      description: Unpack a msgpack body (base64 encoded) returning 'goal clerk inspect'
        output
      operationId: inspect#unpack
      produces:
      - text/plain
      parameters:
      - name: UnpackRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/InspectUnpackRequestBody'
      responses:
        "200":
          description: OK response.
          schema:
            type: string
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/InspectUnpackAccessDeniedResponseBody'
      schemes:
      - http
  /live:
    get:
      tags:
      - info
      summary: live info
      description: Simple health check
      operationId: info#live
      responses:
        "200":
          description: OK response.
      schemes:
      - http
  /openapi3.yaml:
    get:
      tags:
      - info
      summary: Download ./openapi3.yaml
      operationId: info#/openapi3.yaml
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
  /version:
    get:
      tags:
      - info
      summary: version info
      description: Returns version information for the service
      operationId: info#version
      responses:
        "200":
          description: OK response.
          schema:
            type: string
      schemes:
      - http
definitions:
  AccountAddAccessDeniedResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: add_access_denied_response_body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  AccountAddRequestBody:
    title: AccountAddRequestBody
    type: object
    properties:
      address:
        type: array
        items:
          type: string
          example: Explicabo dolorum.
        example:
        - 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        - 6APKHESCBZIAAZBMMZYW3MEHWYBIT3V7XDA2MF45J5TUZG5LXFXFVBJSFY
    example:
      address:
      - 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
      - 6APKHESCBZIAAZBMMZYW3MEHWYBIT3V7XDA2MF45J5TUZG5LXFXFVBJSFY
    required:
    - address
  AccountDeleteAccessDeniedResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: delete_access_denied_response_body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  AccountDeleteAllAccessDeniedResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: deleteAll_access_denied_response_body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  AccountGetAccessDeniedResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: get_access_denied_response_body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  AccountGetMultipleAccessDeniedResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: getMultiple_access_denied_response_body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  AccountGetMultipleRequestBody:
    title: AccountGetMultipleRequestBody
    type: object
    properties:
      address:
        type: array
        items:
          type: string
          example: Cum quod nihil quidem vel magnam.
        example:
        - 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        - 6APKHESCBZIAAZBMMZYW3MEHWYBIT3V7XDA2MF45J5TUZG5LXFXFVBJSFY
    example:
      address:
      - 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
      - 6APKHESCBZIAAZBMMZYW3MEHWYBIT3V7XDA2MF45J5TUZG5LXFXFVBJSFY
    required:
    - address
  AccountGetResponseBody:
    title: AccountGetResponseBody
    type: object
    properties:
      address:
        type: string
        description: Public Account address
        example: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        pattern: ^[A-Z2-7]{58}$
        minLength: 58
        maxLength: 58
      holdings:
        type: object
        description: Account Assets
        example:
          Delectus dicta deserunt accusantium.:
            amount: 171973850282044594
            asset: 202586210
            decimals: 16932959300934428842
            metadataHash: Nihil repellendus explicabo.
            name: Eaque accusamus maxime accusamus veritatis ipsum.
            unitName: Ex laborum laboriosam natus.
            url: Et earum.
          Nisi qui ipsa dolor.:
            amount: 171973850282044594
            asset: 202586210
            decimals: 16932959300934428842
            metadataHash: Nihil repellendus explicabo.
            name: Eaque accusamus maxime accusamus veritatis ipsum.
            unitName: Ex laborum laboriosam natus.
            url: Et earum.
        additionalProperties: true
      round:
        type: integer
        description: Round fetched
        example: 15091227420651452
        format: int64
    example:
      address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
      holdings:
        Consectetur ratione itaque explicabo.:
          amount: 171973850282044594
          asset: 202586210
          decimals: 16932959300934428842
          metadataHash: Nihil repellendus explicabo.
          name: Eaque accusamus maxime accusamus veritatis ipsum.
          unitName: Ex laborum laboriosam natus.
          url: Et earum.
        Omnis eligendi totam.:
          amount: 171973850282044594
          asset: 202586210
          decimals: 16932959300934428842
          metadataHash: Nihil repellendus explicabo.
          name: Eaque accusamus maxime accusamus veritatis ipsum.
          unitName: Ex laborum laboriosam natus.
          url: Et earum.
      round: 4924318997903054619
    required:
    - address
    - round
    - holdings
  AccountIsWatchedAccessDeniedResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: isWatched_access_denied_response_body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  AccountIsWatchedRequestBody:
    title: AccountIsWatchedRequestBody
    type: object
    properties:
      address:
        type: array
        items:
          type: string
          example: Rem enim est.
        example:
        - 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        - 6APKHESCBZIAAZBMMZYW3MEHWYBIT3V7XDA2MF45J5TUZG5LXFXFVBJSFY
    example:
      address:
      - 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
      - 6APKHESCBZIAAZBMMZYW3MEHWYBIT3V7XDA2MF45J5TUZG5LXFXFVBJSFY
    required:
    - address
  AccountListAccessDeniedResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: list_access_denied_response_body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  AccountResponse:
    title: AccountResponse
    type: object
    properties:
      address:
        type: string
        description: Public Account address
        example: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        pattern: ^[A-Z2-7]{58}$
        minLength: 58
        maxLength: 58
      holdings:
        type: object
        description: Account Assets
        example:
          Dolor aut provident.:
            amount: 9015065114807207216
            asset: 202586210
            decimals: 16060864642250952313
            metadataHash: Incidunt iusto id assumenda.
            name: Magnam dignissimos explicabo in aut culpa est.
            unitName: Quia magnam.
            url: Dolores laborum qui quam deleniti veritatis.
          Itaque doloribus.:
            amount: 9015065114807207216
            asset: 202586210
            decimals: 16060864642250952313
            metadataHash: Incidunt iusto id assumenda.
            name: Magnam dignissimos explicabo in aut culpa est.
            unitName: Quia magnam.
            url: Dolores laborum qui quam deleniti veritatis.
        additionalProperties: true
      round:
        type: integer
        description: Round fetched
        example: 16061532530937117821
        format: int64
    description: Account describes an Algorand Account
    example:
      address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
      holdings:
        Tenetur dolor facilis ut in optio.:
          amount: 9015065114807207216
          asset: 202586210
          decimals: 16060864642250952313
          metadataHash: Incidunt iusto id assumenda.
          name: Magnam dignissimos explicabo in aut culpa est.
          unitName: Quia magnam.
          url: Dolores laborum qui quam deleniti veritatis.
      round: 5102997558844952912
    required:
    - address
    - round
    - holdings
  AccountTrackedAccountResponseCollection:
    title: 'Mediatype identifier: application/vnd.algodex.account; type=collection;
      view=default'
    type: array
    items:
      $ref: '#/definitions/TrackedAccountResponse'
    description: ListResponseBody is the result type for an array of TrackedAccountResponse
      (default view)
    example:
    - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
    - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
  InspectUnpackAccessDeniedResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: unpack_access_denied_response_body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  InspectUnpackRequestBody:
    title: InspectUnpackRequestBody
    type: object
    properties:
      msgpack:
        type: string
        example: Itaque ex.
    example:
      msgpack: Dolor reiciendis suscipit consequatur qui.
  TrackedAccountResponse:
    title: 'Mediatype identifier: application/vnd.algodex.account; view=default'
    type: object
    properties:
      address:
        type: string
        description: Public Account address
        example: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        pattern: ^[A-Z2-7]{58}$
        minLength: 58
        maxLength: 58
    description: A TrackedAccount is an Account returned by the indexer (default view)
    example:
      address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
    required:
    - address
