openapi: 3.0.3
info:
  title: AlgoDex Indexer Service
  description: Service for tracking Algorand accounts and currently opted-in Holdings
  version: "1.0"
servers:
- url: http://localhost:80
paths:
  /account:
    get:
      tags:
      - account
      summary: list account
      description: List all tracked accounts
      operationId: account#list
      parameters:
      - name: view
        in: query
        description: View to render
        allowEmptyValue: true
        schema:
          type: string
          description: View to render
          example: default
          enum:
          - default
          - full
        example: default
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                description: 'Response body may alternatively be #/components/schemas/TrackedAccountResponseFullCollection'
                $ref: '#/components/schemas/TrackedAccountCollection'
              example:
              - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
                holdings:
                  Eum expedita ut illum aperiam reiciendis id.:
                    amount: 891370476552451481
                    asset: 202586210
                    decimals: 14649371533185185085
                    metadataHash: Quisquam tempore ex blanditiis aut id necessitatibus.
                    name: UNIT
                    unitName: My Unit
                    url: https://someurl.com
                  Magni molestiae soluta cupiditate.:
                    amount: 891370476552451481
                    asset: 202586210
                    decimals: 14649371533185185085
                    metadataHash: Quisquam tempore ex blanditiis aut id necessitatibus.
                    name: UNIT
                    unitName: My Unit
                    url: https://someurl.com
                round: 17411702549013475276
              - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
                holdings:
                  Eum expedita ut illum aperiam reiciendis id.:
                    amount: 891370476552451481
                    asset: 202586210
                    decimals: 14649371533185185085
                    metadataHash: Quisquam tempore ex blanditiis aut id necessitatibus.
                    name: UNIT
                    unitName: My Unit
                    url: https://someurl.com
                  Magni molestiae soluta cupiditate.:
                    amount: 891370476552451481
                    asset: 202586210
                    decimals: 14649371533185185085
                    metadataHash: Quisquam tempore ex blanditiis aut id necessitatibus.
                    name: UNIT
                    unitName: My Unit
                    url: https://someurl.com
                round: 17411702549013475276
        "401":
          description: Unauthorized response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
    post:
      tags:
      - account
      summary: add account
      description: Add Algorand account(s) to track
      operationId: account#add
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddRequestBody'
            example:
              address:
              - 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
              - 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
      responses:
        "200":
          description: OK response.
        "401":
          description: Unauthorized response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /account/{address}:
    delete:
      tags:
      - account
      summary: delete account
      description: Delete Algorand account(s) to track
      operationId: account#delete
      parameters:
      - name: address
        in: path
        required: true
        schema:
          type: array
          items:
            type: string
            example: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
            pattern: ^[A-Z2-7]{58}$
            minLength: 58
            maxLength: 58
          example:
          - 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
          - 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
          - 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        example:
        - 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        - 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
      responses:
        "200":
          description: OK response.
        "401":
          description: Unauthorized response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
    get:
      tags:
      - account
      summary: get account
      description: Get specific account
      operationId: account#get
      parameters:
      - name: address
        in: path
        description: Public Account address
        required: true
        schema:
          type: string
          description: Public Account address
          example: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
          pattern: ^[A-Z2-7]{58}$
          minLength: 58
          maxLength: 58
        example: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
              example:
                address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
                holdings:
                  Eaque accusamus maxime accusamus veritatis ipsum.:
                    amount: 2530183614445484651
                    asset: 202586210
                    decimals: 13341261648726274623
                    metadataHash: Blanditiis ut ea est esse.
                    name: UNIT
                    unitName: My Unit
                    url: https://someurl.com
                  Ex laborum laboriosam natus.:
                    amount: 2530183614445484651
                    asset: 202586210
                    decimals: 13341261648726274623
                    metadataHash: Blanditiis ut ea est esse.
                    name: UNIT
                    unitName: My Unit
                    url: https://someurl.com
                  Nihil repellendus explicabo.:
                    amount: 2530183614445484651
                    asset: 202586210
                    decimals: 13341261648726274623
                    metadataHash: Blanditiis ut ea est esse.
                    name: UNIT
                    unitName: My Unit
                    url: https://someurl.com
                round: 171973850282044594
        "401":
          description: Unauthorized response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /account/all:
    delete:
      tags:
      - account
      summary: deleteAll account
      description: Delete all tracked algorand account(s).  Used for resetting everything
      operationId: account#deleteAll
      responses:
        "200":
          description: OK response.
        "401":
          description: Unauthorized response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /account/get:
    post:
      tags:
      - account
      summary: getMultiple account
      description: Get account(s)
      operationId: account#getMultiple
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddRequestBody'
            example:
              address:
              - 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
              - 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
                example:
                - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
                  holdings:
                    Error quam tenetur id aliquid.:
                      amount: 799206650352541578
                      asset: 202586210
                      decimals: 6176359929065967441
                      metadataHash: Maiores aut quo commodi enim.
                      name: UNIT
                      unitName: My Unit
                      url: https://someurl.com
                    Perspiciatis deserunt.:
                      amount: 799206650352541578
                      asset: 202586210
                      decimals: 6176359929065967441
                      metadataHash: Maiores aut quo commodi enim.
                      name: UNIT
                      unitName: My Unit
                      url: https://someurl.com
                  round: 511372126505206655
                - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
                  holdings:
                    Error quam tenetur id aliquid.:
                      amount: 799206650352541578
                      asset: 202586210
                      decimals: 6176359929065967441
                      metadataHash: Maiores aut quo commodi enim.
                      name: UNIT
                      unitName: My Unit
                      url: https://someurl.com
                    Perspiciatis deserunt.:
                      amount: 799206650352541578
                      asset: 202586210
                      decimals: 6176359929065967441
                      metadataHash: Maiores aut quo commodi enim.
                      name: UNIT
                      unitName: My Unit
                      url: https://someurl.com
                  round: 511372126505206655
                - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
                  holdings:
                    Error quam tenetur id aliquid.:
                      amount: 799206650352541578
                      asset: 202586210
                      decimals: 6176359929065967441
                      metadataHash: Maiores aut quo commodi enim.
                      name: UNIT
                      unitName: My Unit
                      url: https://someurl.com
                    Perspiciatis deserunt.:
                      amount: 799206650352541578
                      asset: 202586210
                      decimals: 6176359929065967441
                      metadataHash: Maiores aut quo commodi enim.
                      name: UNIT
                      unitName: My Unit
                      url: https://someurl.com
                  round: 511372126505206655
                - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
                  holdings:
                    Error quam tenetur id aliquid.:
                      amount: 799206650352541578
                      asset: 202586210
                      decimals: 6176359929065967441
                      metadataHash: Maiores aut quo commodi enim.
                      name: UNIT
                      unitName: My Unit
                      url: https://someurl.com
                    Perspiciatis deserunt.:
                      amount: 799206650352541578
                      asset: 202586210
                      decimals: 6176359929065967441
                      metadataHash: Maiores aut quo commodi enim.
                      name: UNIT
                      unitName: My Unit
                      url: https://someurl.com
                  round: 511372126505206655
              example:
              - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
                holdings:
                  Error quam tenetur id aliquid.:
                    amount: 799206650352541578
                    asset: 202586210
                    decimals: 6176359929065967441
                    metadataHash: Maiores aut quo commodi enim.
                    name: UNIT
                    unitName: My Unit
                    url: https://someurl.com
                  Perspiciatis deserunt.:
                    amount: 799206650352541578
                    asset: 202586210
                    decimals: 6176359929065967441
                    metadataHash: Maiores aut quo commodi enim.
                    name: UNIT
                    unitName: My Unit
                    url: https://someurl.com
                round: 511372126505206655
              - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
                holdings:
                  Error quam tenetur id aliquid.:
                    amount: 799206650352541578
                    asset: 202586210
                    decimals: 6176359929065967441
                    metadataHash: Maiores aut quo commodi enim.
                    name: UNIT
                    unitName: My Unit
                    url: https://someurl.com
                  Perspiciatis deserunt.:
                    amount: 799206650352541578
                    asset: 202586210
                    decimals: 6176359929065967441
                    metadataHash: Maiores aut quo commodi enim.
                    name: UNIT
                    unitName: My Unit
                    url: https://someurl.com
                round: 511372126505206655
        "401":
          description: Unauthorized response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /account/isWatched:
    post:
      tags:
      - account
      summary: isWatched account
      description: Returns which of the passed accounts are currently being monitored
      operationId: account#isWatched
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddRequestBody'
            example:
              address:
              - 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
              - 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
              - 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: Aut debitis neque odit rem maxime illum.
                example:
                - Quo non veniam illum sit.
                - Aut est nesciunt aspernatur.
              example:
              - Voluptatem quod sint est occaecati.
              - Velit non nihil in.
              - Quis vero.
              - Voluptate provident enim esse itaque reprehenderit.
        "401":
          description: Unauthorized response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /inspect/unpack:
    post:
      tags:
      - inspect
      summary: unpack inspect
      description: Unpack a msgpack body (base64 encoded) returning 'goal clerk inspect'
        output
      operationId: inspect#unpack
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UnpackRequestBody'
            example:
              msgpack: Placeat quidem blanditiis dolorem officiis aspernatur.
      responses:
        "200":
          description: OK response.
          content:
            text/plain:
              schema:
                type: string
                description: Returns output from goal clerk inspect of passed msgpack-encoded
                  payload
                example: Eum dolor repellendus.
              example: Tempore delectus et.
        "401":
          description: Unauthorized response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /live:
    get:
      tags:
      - info
      summary: live info
      description: Simple health check
      operationId: info#live
      responses:
        "200":
          description: OK response.
  /openapi3.yaml:
    get:
      tags:
      - info
      summary: Download ./openapi3.yaml
      operationId: info#/openapi3.yaml
      responses:
        "200":
          description: File downloaded
  /orders:
    get:
      tags:
      - orders
      summary: get orders
      description: Get all open orders for a specific asset
      operationId: orders#get
      parameters:
      - name: assetId
        in: query
        description: ASA ID
        allowEmptyValue: true
        schema:
          type: integer
          description: ASA ID
          example: 15322902
        example: 15322902
      - name: ownerAddr
        in: query
        description: Owner address(es)
        allowEmptyValue: true
        schema:
          type: array
          items:
            type: string
            example: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
            pattern: ^[A-Z2-7]{58}$
            minLength: 58
            maxLength: 58
          description: Owner address(es)
          example:
          - 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
          - 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
          - 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        example:
        - 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        - 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Orders'
              example:
                buyASAOrdersInEscrow:
                - algoAmount: 498000
                  appId: 16021157
                  asaAmount: 1000000
                  asaPrice: ".08"
                  assetId: 15322902
                  assetLimitPriceD: 197
                  assetLimitPriceInAlgos: ".08"
                  assetLimitPriceN: 100
                  decimals: 6
                  escrowAddress: 2IYBUR4WXPWGBKRETN4GVSCPG7VOJRMVZFYTDYMQSRMXQJY24EHGFLFIMU
                  formattedASAAmount: "1.000000"
                  formattedPrice: "1.970000"
                  minimumExecutionSizeInAlgo: 0
                  ownerAddress: XHGANA4SOVZKH4GGSSLAMOZDVWWVIXT5DZBIEGI3GX2EESVFNFGFTHJATA
                  round: 16043694
                  unix_time: 1629064223
                - algoAmount: 498000
                  appId: 16021157
                  asaAmount: 1000000
                  asaPrice: ".08"
                  assetId: 15322902
                  assetLimitPriceD: 197
                  assetLimitPriceInAlgos: ".08"
                  assetLimitPriceN: 100
                  decimals: 6
                  escrowAddress: 2IYBUR4WXPWGBKRETN4GVSCPG7VOJRMVZFYTDYMQSRMXQJY24EHGFLFIMU
                  formattedASAAmount: "1.000000"
                  formattedPrice: "1.970000"
                  minimumExecutionSizeInAlgo: 0
                  ownerAddress: XHGANA4SOVZKH4GGSSLAMOZDVWWVIXT5DZBIEGI3GX2EESVFNFGFTHJATA
                  round: 16043694
                  unix_time: 1629064223
                sellASAOrdersInEscrow:
                - algoAmount: 498000
                  appId: 16021157
                  asaAmount: 1000000
                  asaPrice: ".08"
                  assetId: 15322902
                  assetLimitPriceD: 197
                  assetLimitPriceInAlgos: ".08"
                  assetLimitPriceN: 100
                  decimals: 6
                  escrowAddress: 2IYBUR4WXPWGBKRETN4GVSCPG7VOJRMVZFYTDYMQSRMXQJY24EHGFLFIMU
                  formattedASAAmount: "1.000000"
                  formattedPrice: "1.970000"
                  minimumExecutionSizeInAlgo: 0
                  ownerAddress: XHGANA4SOVZKH4GGSSLAMOZDVWWVIXT5DZBIEGI3GX2EESVFNFGFTHJATA
                  round: 16043694
                  unix_time: 1629064223
                - algoAmount: 498000
                  appId: 16021157
                  asaAmount: 1000000
                  asaPrice: ".08"
                  assetId: 15322902
                  assetLimitPriceD: 197
                  assetLimitPriceInAlgos: ".08"
                  assetLimitPriceN: 100
                  decimals: 6
                  escrowAddress: 2IYBUR4WXPWGBKRETN4GVSCPG7VOJRMVZFYTDYMQSRMXQJY24EHGFLFIMU
                  formattedASAAmount: "1.000000"
                  formattedPrice: "1.970000"
                  minimumExecutionSizeInAlgo: 0
                  ownerAddress: XHGANA4SOVZKH4GGSSLAMOZDVWWVIXT5DZBIEGI3GX2EESVFNFGFTHJATA
                  round: 16043694
                  unix_time: 1629064223
                - algoAmount: 498000
                  appId: 16021157
                  asaAmount: 1000000
                  asaPrice: ".08"
                  assetId: 15322902
                  assetLimitPriceD: 197
                  assetLimitPriceInAlgos: ".08"
                  assetLimitPriceN: 100
                  decimals: 6
                  escrowAddress: 2IYBUR4WXPWGBKRETN4GVSCPG7VOJRMVZFYTDYMQSRMXQJY24EHGFLFIMU
                  formattedASAAmount: "1.000000"
                  formattedPrice: "1.970000"
                  minimumExecutionSizeInAlgo: 0
                  ownerAddress: XHGANA4SOVZKH4GGSSLAMOZDVWWVIXT5DZBIEGI3GX2EESVFNFGFTHJATA
                  round: 16043694
                  unix_time: 1629064223
        "401":
          description: Unauthorized response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /version:
    get:
      tags:
      - info
      summary: version info
      description: Returns version information for the service
      operationId: info#version
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: string
                example: 14193a3-dirty
              example: 14193a3-dirty
components:
  schemas:
    Account:
      type: object
      properties:
        address:
          type: string
          description: Public Account address
          example: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
          pattern: ^[A-Z2-7]{58}$
          minLength: 58
          maxLength: 58
        holdings:
          type: object
          description: Account Assets
          example:
            Quae exercitationem numquam mollitia nihil.:
              amount: 2530183614445484651
              asset: 202586210
              decimals: 13341261648726274623
              metadataHash: Blanditiis ut ea est esse.
              name: UNIT
              unitName: My Unit
              url: https://someurl.com
          additionalProperties: true
        round:
          type: integer
          description: Round fetched
          example: 12558238732144386939
      example:
        address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        holdings:
          Ipsam suscipit.:
            amount: 2530183614445484651
            asset: 202586210
            decimals: 13341261648726274623
            metadataHash: Blanditiis ut ea est esse.
            name: UNIT
            unitName: My Unit
            url: https://someurl.com
          Sint voluptatem aliquam.:
            amount: 2530183614445484651
            asset: 202586210
            decimals: 13341261648726274623
            metadataHash: Blanditiis ut ea est esse.
            name: UNIT
            unitName: My Unit
            url: https://someurl.com
        round: 12375541992404790039
      required:
      - address
      - round
      - holdings
    AddRequestBody:
      type: object
      properties:
        address:
          type: array
          items:
            type: string
            example: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
            pattern: ^[A-Z2-7]{58}$
            minLength: 58
            maxLength: 58
          example:
          - 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
          - 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
          - 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
      example:
        address:
        - 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        - 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        - 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        - 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
      required:
      - address
    AlgodexAccount:
      type: object
      properties:
        address:
          type: string
          description: Public Account address
          example: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
          pattern: ^[A-Z2-7]{58}$
          minLength: 58
          maxLength: 58
        holdings:
          type: object
          description: Account Assets
          example:
            Enim est enim qui et.:
              amount: 799206650352541578
              asset: 202586210
              decimals: 6176359929065967441
              metadataHash: Maiores aut quo commodi enim.
              name: UNIT
              unitName: My Unit
              url: https://someurl.com
            Voluptate dolore accusantium itaque ex eaque.:
              amount: 799206650352541578
              asset: 202586210
              decimals: 6176359929065967441
              metadataHash: Maiores aut quo commodi enim.
              name: UNIT
              unitName: My Unit
              url: https://someurl.com
          additionalProperties: true
        round:
          type: integer
          description: Round fetched
          example: 4404760265905385542
      description: A TrackedAccount is an Account returned by the indexer
      example:
        address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        holdings:
          Consequatur qui natus dicta consectetur iusto soluta.:
            amount: 799206650352541578
            asset: 202586210
            decimals: 6176359929065967441
            metadataHash: Maiores aut quo commodi enim.
            name: UNIT
            unitName: My Unit
            url: https://someurl.com
          Est tempore.:
            amount: 799206650352541578
            asset: 202586210
            decimals: 6176359929065967441
            metadataHash: Maiores aut quo commodi enim.
            name: UNIT
            unitName: My Unit
            url: https://someurl.com
        round: 3288932136941885007
      required:
      - address
      - round
      - holdings
    Error:
      type: object
      properties:
        fault:
          type: boolean
          description: Is the error a server-side fault?
          example: true
        id:
          type: string
          description: ID is a unique identifier for this particular occurrence of
            the problem.
          example: 123abc
        message:
          type: string
          description: Message is a human-readable explanation specific to this occurrence
            of the problem.
          example: parameter 'p' must be an integer
        name:
          type: string
          description: Name is the name of this class of errors.
          example: bad_request
        temporary:
          type: boolean
          description: Is the error temporary?
          example: false
        timeout:
          type: boolean
          description: Is the error a timeout?
          example: false
      example:
        id: 3F1FKVRR
        message: Value of ID must be an integer
        name: bad_request
      required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
    Order:
      type: object
      properties:
        algoAmount:
          type: integer
          example: 498000
        appId:
          type: integer
          example: 16021157
        asaAmount:
          type: integer
          example: 1000000
        asaPrice:
          type: string
          example: ".08"
        assetId:
          type: integer
          example: 15322902
        assetLimitPriceD:
          type: integer
          example: 197
        assetLimitPriceInAlgos:
          type: string
          example: ".08"
        assetLimitPriceN:
          type: integer
          example: 100
        decimals:
          type: integer
          example: 6
        escrowAddress:
          type: string
          example: 2IYBUR4WXPWGBKRETN4GVSCPG7VOJRMVZFYTDYMQSRMXQJY24EHGFLFIMU
        formattedASAAmount:
          type: string
          example: "1.000000"
        formattedPrice:
          type: string
          example: "1.970000"
        minimumExecutionSizeInAlgo:
          type: integer
          example: 0
        ownerAddress:
          type: string
          example: XHGANA4SOVZKH4GGSSLAMOZDVWWVIXT5DZBIEGI3GX2EESVFNFGFTHJATA
        round:
          type: integer
          example: 16043694
        unix_time:
          type: integer
          example: 1629064223
      description: Order is an individual buy or sell order
      example:
        algoAmount: 498000
        appId: 16021157
        asaAmount: 1000000
        asaPrice: ".08"
        assetId: 15322902
        assetLimitPriceD: 197
        assetLimitPriceInAlgos: ".08"
        assetLimitPriceN: 100
        decimals: 6
        escrowAddress: 2IYBUR4WXPWGBKRETN4GVSCPG7VOJRMVZFYTDYMQSRMXQJY24EHGFLFIMU
        formattedASAAmount: "1.000000"
        formattedPrice: "1.970000"
        minimumExecutionSizeInAlgo: 0
        ownerAddress: XHGANA4SOVZKH4GGSSLAMOZDVWWVIXT5DZBIEGI3GX2EESVFNFGFTHJATA
        round: 16043694
        unix_time: 1629064223
      required:
      - assetLimitPriceInAlgos
      - asaPrice
      - assetLimitPriceD
      - assetLimitPriceN
      - algoAmount
      - asaAmount
      - assetId
      - appId
      - escrowAddress
      - ownerAddress
      - minimumExecutionSizeInAlgo
      - round
      - unix_time
      - formattedPrice
      - formattedASAAmount
      - decimals
    Orders:
      type: object
      properties:
        buyASAOrdersInEscrow:
          type: array
          items:
            $ref: '#/components/schemas/Order'
          description: Buy orders
          example:
          - algoAmount: 498000
            appId: 16021157
            asaAmount: 1000000
            asaPrice: ".08"
            assetId: 15322902
            assetLimitPriceD: 197
            assetLimitPriceInAlgos: ".08"
            assetLimitPriceN: 100
            decimals: 6
            escrowAddress: 2IYBUR4WXPWGBKRETN4GVSCPG7VOJRMVZFYTDYMQSRMXQJY24EHGFLFIMU
            formattedASAAmount: "1.000000"
            formattedPrice: "1.970000"
            minimumExecutionSizeInAlgo: 0
            ownerAddress: XHGANA4SOVZKH4GGSSLAMOZDVWWVIXT5DZBIEGI3GX2EESVFNFGFTHJATA
            round: 16043694
            unix_time: 1629064223
          - algoAmount: 498000
            appId: 16021157
            asaAmount: 1000000
            asaPrice: ".08"
            assetId: 15322902
            assetLimitPriceD: 197
            assetLimitPriceInAlgos: ".08"
            assetLimitPriceN: 100
            decimals: 6
            escrowAddress: 2IYBUR4WXPWGBKRETN4GVSCPG7VOJRMVZFYTDYMQSRMXQJY24EHGFLFIMU
            formattedASAAmount: "1.000000"
            formattedPrice: "1.970000"
            minimumExecutionSizeInAlgo: 0
            ownerAddress: XHGANA4SOVZKH4GGSSLAMOZDVWWVIXT5DZBIEGI3GX2EESVFNFGFTHJATA
            round: 16043694
            unix_time: 1629064223
          - algoAmount: 498000
            appId: 16021157
            asaAmount: 1000000
            asaPrice: ".08"
            assetId: 15322902
            assetLimitPriceD: 197
            assetLimitPriceInAlgos: ".08"
            assetLimitPriceN: 100
            decimals: 6
            escrowAddress: 2IYBUR4WXPWGBKRETN4GVSCPG7VOJRMVZFYTDYMQSRMXQJY24EHGFLFIMU
            formattedASAAmount: "1.000000"
            formattedPrice: "1.970000"
            minimumExecutionSizeInAlgo: 0
            ownerAddress: XHGANA4SOVZKH4GGSSLAMOZDVWWVIXT5DZBIEGI3GX2EESVFNFGFTHJATA
            round: 16043694
            unix_time: 1629064223
          - algoAmount: 498000
            appId: 16021157
            asaAmount: 1000000
            asaPrice: ".08"
            assetId: 15322902
            assetLimitPriceD: 197
            assetLimitPriceInAlgos: ".08"
            assetLimitPriceN: 100
            decimals: 6
            escrowAddress: 2IYBUR4WXPWGBKRETN4GVSCPG7VOJRMVZFYTDYMQSRMXQJY24EHGFLFIMU
            formattedASAAmount: "1.000000"
            formattedPrice: "1.970000"
            minimumExecutionSizeInAlgo: 0
            ownerAddress: XHGANA4SOVZKH4GGSSLAMOZDVWWVIXT5DZBIEGI3GX2EESVFNFGFTHJATA
            round: 16043694
            unix_time: 1629064223
        sellASAOrdersInEscrow:
          type: array
          items:
            $ref: '#/components/schemas/Order'
          description: Sell orders
          example:
          - algoAmount: 498000
            appId: 16021157
            asaAmount: 1000000
            asaPrice: ".08"
            assetId: 15322902
            assetLimitPriceD: 197
            assetLimitPriceInAlgos: ".08"
            assetLimitPriceN: 100
            decimals: 6
            escrowAddress: 2IYBUR4WXPWGBKRETN4GVSCPG7VOJRMVZFYTDYMQSRMXQJY24EHGFLFIMU
            formattedASAAmount: "1.000000"
            formattedPrice: "1.970000"
            minimumExecutionSizeInAlgo: 0
            ownerAddress: XHGANA4SOVZKH4GGSSLAMOZDVWWVIXT5DZBIEGI3GX2EESVFNFGFTHJATA
            round: 16043694
            unix_time: 1629064223
          - algoAmount: 498000
            appId: 16021157
            asaAmount: 1000000
            asaPrice: ".08"
            assetId: 15322902
            assetLimitPriceD: 197
            assetLimitPriceInAlgos: ".08"
            assetLimitPriceN: 100
            decimals: 6
            escrowAddress: 2IYBUR4WXPWGBKRETN4GVSCPG7VOJRMVZFYTDYMQSRMXQJY24EHGFLFIMU
            formattedASAAmount: "1.000000"
            formattedPrice: "1.970000"
            minimumExecutionSizeInAlgo: 0
            ownerAddress: XHGANA4SOVZKH4GGSSLAMOZDVWWVIXT5DZBIEGI3GX2EESVFNFGFTHJATA
            round: 16043694
            unix_time: 1629064223
          - algoAmount: 498000
            appId: 16021157
            asaAmount: 1000000
            asaPrice: ".08"
            assetId: 15322902
            assetLimitPriceD: 197
            assetLimitPriceInAlgos: ".08"
            assetLimitPriceN: 100
            decimals: 6
            escrowAddress: 2IYBUR4WXPWGBKRETN4GVSCPG7VOJRMVZFYTDYMQSRMXQJY24EHGFLFIMU
            formattedASAAmount: "1.000000"
            formattedPrice: "1.970000"
            minimumExecutionSizeInAlgo: 0
            ownerAddress: XHGANA4SOVZKH4GGSSLAMOZDVWWVIXT5DZBIEGI3GX2EESVFNFGFTHJATA
            round: 16043694
            unix_time: 1629064223
          - algoAmount: 498000
            appId: 16021157
            asaAmount: 1000000
            asaPrice: ".08"
            assetId: 15322902
            assetLimitPriceD: 197
            assetLimitPriceInAlgos: ".08"
            assetLimitPriceN: 100
            decimals: 6
            escrowAddress: 2IYBUR4WXPWGBKRETN4GVSCPG7VOJRMVZFYTDYMQSRMXQJY24EHGFLFIMU
            formattedASAAmount: "1.000000"
            formattedPrice: "1.970000"
            minimumExecutionSizeInAlgo: 0
            ownerAddress: XHGANA4SOVZKH4GGSSLAMOZDVWWVIXT5DZBIEGI3GX2EESVFNFGFTHJATA
            round: 16043694
            unix_time: 1629064223
      example:
        buyASAOrdersInEscrow:
        - algoAmount: 498000
          appId: 16021157
          asaAmount: 1000000
          asaPrice: ".08"
          assetId: 15322902
          assetLimitPriceD: 197
          assetLimitPriceInAlgos: ".08"
          assetLimitPriceN: 100
          decimals: 6
          escrowAddress: 2IYBUR4WXPWGBKRETN4GVSCPG7VOJRMVZFYTDYMQSRMXQJY24EHGFLFIMU
          formattedASAAmount: "1.000000"
          formattedPrice: "1.970000"
          minimumExecutionSizeInAlgo: 0
          ownerAddress: XHGANA4SOVZKH4GGSSLAMOZDVWWVIXT5DZBIEGI3GX2EESVFNFGFTHJATA
          round: 16043694
          unix_time: 1629064223
        - algoAmount: 498000
          appId: 16021157
          asaAmount: 1000000
          asaPrice: ".08"
          assetId: 15322902
          assetLimitPriceD: 197
          assetLimitPriceInAlgos: ".08"
          assetLimitPriceN: 100
          decimals: 6
          escrowAddress: 2IYBUR4WXPWGBKRETN4GVSCPG7VOJRMVZFYTDYMQSRMXQJY24EHGFLFIMU
          formattedASAAmount: "1.000000"
          formattedPrice: "1.970000"
          minimumExecutionSizeInAlgo: 0
          ownerAddress: XHGANA4SOVZKH4GGSSLAMOZDVWWVIXT5DZBIEGI3GX2EESVFNFGFTHJATA
          round: 16043694
          unix_time: 1629064223
        sellASAOrdersInEscrow:
        - algoAmount: 498000
          appId: 16021157
          asaAmount: 1000000
          asaPrice: ".08"
          assetId: 15322902
          assetLimitPriceD: 197
          assetLimitPriceInAlgos: ".08"
          assetLimitPriceN: 100
          decimals: 6
          escrowAddress: 2IYBUR4WXPWGBKRETN4GVSCPG7VOJRMVZFYTDYMQSRMXQJY24EHGFLFIMU
          formattedASAAmount: "1.000000"
          formattedPrice: "1.970000"
          minimumExecutionSizeInAlgo: 0
          ownerAddress: XHGANA4SOVZKH4GGSSLAMOZDVWWVIXT5DZBIEGI3GX2EESVFNFGFTHJATA
          round: 16043694
          unix_time: 1629064223
        - algoAmount: 498000
          appId: 16021157
          asaAmount: 1000000
          asaPrice: ".08"
          assetId: 15322902
          assetLimitPriceD: 197
          assetLimitPriceInAlgos: ".08"
          assetLimitPriceN: 100
          decimals: 6
          escrowAddress: 2IYBUR4WXPWGBKRETN4GVSCPG7VOJRMVZFYTDYMQSRMXQJY24EHGFLFIMU
          formattedASAAmount: "1.000000"
          formattedPrice: "1.970000"
          minimumExecutionSizeInAlgo: 0
          ownerAddress: XHGANA4SOVZKH4GGSSLAMOZDVWWVIXT5DZBIEGI3GX2EESVFNFGFTHJATA
          round: 16043694
          unix_time: 1629064223
        - algoAmount: 498000
          appId: 16021157
          asaAmount: 1000000
          asaPrice: ".08"
          assetId: 15322902
          assetLimitPriceD: 197
          assetLimitPriceInAlgos: ".08"
          assetLimitPriceN: 100
          decimals: 6
          escrowAddress: 2IYBUR4WXPWGBKRETN4GVSCPG7VOJRMVZFYTDYMQSRMXQJY24EHGFLFIMU
          formattedASAAmount: "1.000000"
          formattedPrice: "1.970000"
          minimumExecutionSizeInAlgo: 0
          ownerAddress: XHGANA4SOVZKH4GGSSLAMOZDVWWVIXT5DZBIEGI3GX2EESVFNFGFTHJATA
          round: 16043694
          unix_time: 1629064223
    TrackedAccountCollection:
      type: array
      items:
        $ref: '#/components/schemas/AlgodexAccount'
      example:
      - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        holdings:
          Eum expedita ut illum aperiam reiciendis id.:
            amount: 891370476552451481
            asset: 202586210
            decimals: 14649371533185185085
            metadataHash: Quisquam tempore ex blanditiis aut id necessitatibus.
            name: UNIT
            unitName: My Unit
            url: https://someurl.com
          Magni molestiae soluta cupiditate.:
            amount: 891370476552451481
            asset: 202586210
            decimals: 14649371533185185085
            metadataHash: Quisquam tempore ex blanditiis aut id necessitatibus.
            name: UNIT
            unitName: My Unit
            url: https://someurl.com
        round: 17411702549013475276
      - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        holdings:
          Eum expedita ut illum aperiam reiciendis id.:
            amount: 891370476552451481
            asset: 202586210
            decimals: 14649371533185185085
            metadataHash: Quisquam tempore ex blanditiis aut id necessitatibus.
            name: UNIT
            unitName: My Unit
            url: https://someurl.com
          Magni molestiae soluta cupiditate.:
            amount: 891370476552451481
            asset: 202586210
            decimals: 14649371533185185085
            metadataHash: Quisquam tempore ex blanditiis aut id necessitatibus.
            name: UNIT
            unitName: My Unit
            url: https://someurl.com
        round: 17411702549013475276
      - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        holdings:
          Eum expedita ut illum aperiam reiciendis id.:
            amount: 891370476552451481
            asset: 202586210
            decimals: 14649371533185185085
            metadataHash: Quisquam tempore ex blanditiis aut id necessitatibus.
            name: UNIT
            unitName: My Unit
            url: https://someurl.com
          Magni molestiae soluta cupiditate.:
            amount: 891370476552451481
            asset: 202586210
            decimals: 14649371533185185085
            metadataHash: Quisquam tempore ex blanditiis aut id necessitatibus.
            name: UNIT
            unitName: My Unit
            url: https://someurl.com
        round: 17411702549013475276
      - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        holdings:
          Eum expedita ut illum aperiam reiciendis id.:
            amount: 891370476552451481
            asset: 202586210
            decimals: 14649371533185185085
            metadataHash: Quisquam tempore ex blanditiis aut id necessitatibus.
            name: UNIT
            unitName: My Unit
            url: https://someurl.com
          Magni molestiae soluta cupiditate.:
            amount: 891370476552451481
            asset: 202586210
            decimals: 14649371533185185085
            metadataHash: Quisquam tempore ex blanditiis aut id necessitatibus.
            name: UNIT
            unitName: My Unit
            url: https://someurl.com
        round: 17411702549013475276
    TrackedAccountResponseFull:
      type: object
      properties:
        address:
          type: string
          description: Public Account address
          example: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
          pattern: ^[A-Z2-7]{58}$
          minLength: 58
          maxLength: 58
        holdings:
          type: object
          description: Account Assets
          example:
            Sed vel ullam.:
              amount: 799206650352541578
              asset: 202586210
              decimals: 6176359929065967441
              metadataHash: Maiores aut quo commodi enim.
              name: UNIT
              unitName: My Unit
              url: https://someurl.com
            Sit quis adipisci quibusdam.:
              amount: 799206650352541578
              asset: 202586210
              decimals: 6176359929065967441
              metadataHash: Maiores aut quo commodi enim.
              name: UNIT
              unitName: My Unit
              url: https://someurl.com
          additionalProperties: true
        round:
          type: integer
          description: Round fetched
          example: 17151966803213858919
      description: A TrackedAccount is an Account returned by the indexer (full view)
      example:
        address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        holdings:
          Deserunt in illo.:
            amount: 799206650352541578
            asset: 202586210
            decimals: 6176359929065967441
            metadataHash: Maiores aut quo commodi enim.
            name: UNIT
            unitName: My Unit
            url: https://someurl.com
          Eum ab soluta quos et ut.:
            amount: 799206650352541578
            asset: 202586210
            decimals: 6176359929065967441
            metadataHash: Maiores aut quo commodi enim.
            name: UNIT
            unitName: My Unit
            url: https://someurl.com
        round: 986436392202290993
      required:
      - address
      - round
      - holdings
    TrackedAccountResponseFullCollection:
      type: array
      items:
        $ref: '#/components/schemas/TrackedAccountResponseFull'
      description: ListResponseBody is the result type for an array of TrackedAccountResponse
        (full view)
      example:
      - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        holdings:
          Dignissimos id soluta nesciunt voluptatibus voluptatem nesciunt.:
            amount: 799206650352541578
            asset: 202586210
            decimals: 6176359929065967441
            metadataHash: Maiores aut quo commodi enim.
            name: UNIT
            unitName: My Unit
            url: https://someurl.com
        round: 27042102648704077
      - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        holdings:
          Dignissimos id soluta nesciunt voluptatibus voluptatem nesciunt.:
            amount: 799206650352541578
            asset: 202586210
            decimals: 6176359929065967441
            metadataHash: Maiores aut quo commodi enim.
            name: UNIT
            unitName: My Unit
            url: https://someurl.com
        round: 27042102648704077
      - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        holdings:
          Dignissimos id soluta nesciunt voluptatibus voluptatem nesciunt.:
            amount: 799206650352541578
            asset: 202586210
            decimals: 6176359929065967441
            metadataHash: Maiores aut quo commodi enim.
            name: UNIT
            unitName: My Unit
            url: https://someurl.com
        round: 27042102648704077
    UnpackRequestBody:
      type: object
      properties:
        msgpack:
          type: string
          example: Quia dolorem non.
      example:
        msgpack: Aspernatur quis culpa neque saepe facilis.
tags:
- name: account
  description: The account service specifies which Algorand accounts to track
- name: orders
  description: The orders service provides information on open orders
- name: inspect
  description: The inspect service provides msgpack decoding services
- name: info
  description: The info service provides information on version data, liveness, readiness
    checks, etc.
